### ISSUE TITLE
Feature request: Option for disabling storage of form data in results AND submission table

### ISSUE THREAD

**Issue by digitalbricks** [WebsiteBaker-modules/mpform#7]
With the upcoming General Data Protection Regulation (GDPR) or – in german – Datenschutz-Grundverordnung (DSGVO), it would be great to have an option for totally disabling the storage of form entries in the MySQL database of the CMS.

As stated in the module options, we can already disable the storage in a results table by setting the name for the result table to DISABLED – but the submission table on the other hand would still store all entries.

**Comment by mrbaseman** [comment]
This is already possible since version 1.3.19 (see [CHANGELOG.txt](https://github.com/WebsiteBaker-modules/mpform/blob/master/CHANGELOG.txt)): 
* You just have to go to "general settings", "Workflow Settings" and remove all the content of the template in the box "Data transfer to mpform_submissions table" and save the settings.
* You can also go to "Advanced Settings" and in the section "SPAM Protection" set the "Submissions stored in Database" to 0 and save the advanced settings. 

The first method stops saving submissions to the submission table of the current form, the second one has a larger impact, namely the next submission would wipe out all data in the submission_table and in the results_table if the suffix not already set to "DISABLED". 

I'm going to close this issue. Please feel free to reopen if you still face problems with the above instructions in one of the latest versions of mpForm.

**Comment by digitalbricks** [comment]
@mrbaseman 
Thank you for giving me that hint! 
Great to see that this is already implemented.
